export const scenarios = {
  complete: {
    id: "complete",
    title: "Maker-first, then finish",
    subtitle: "The order adapts and reaches its target inside the budget",
    symbol: "BNBUSDT",
    side: "BUY",
    quoteAmount: 500,
    maxSlippageBps: 15,
    deadlineSeconds: 180,
    minCompletionPct: 80,
    marketMode: "live",
    simulatedFills: [0.34, 0.51, 0.15],
    market: { symbol: "BNBUSDT", bid: 755.80, ask: 755.99, midpoint: 755.895, spreadBps: 2.5, dailyQuoteVolume: 180000000, priceChangePercent24h: 1.8, source: "Demo fixture" },
    prompt: "Buy $500 of BNB in three minutes. Prefer maker execution, but complete at least 80% and never cross 15 bps.",
  },
  boundary: {
    id: "boundary",
    title: "Protect the price ceiling",
    subtitle: "The agent stops instead of paying for a bad fill",
    symbol: "BTCUSDT",
    side: "BUY",
    quoteAmount: 1000,
    maxSlippageBps: 8,
    deadlineSeconds: 120,
    minCompletionPct: 80,
    marketMode: "stress",
    simulatedFills: [0.42, 0.20, 0],
    market: { symbol: "BTCUSDT", bid: 110000, ask: 110250, midpoint: 110125, spreadBps: 22.7, dailyQuoteVolume: 850000000, priceChangePercent24h: -2.4, source: "Guardian stress-test fixture" },
    prompt: "Buy $1,000 of BTC within two minutes, but do not exceed 8 bps of slippage.",
  },
  partial: {
    id: "partial",
    title: "Honest partial completion",
    subtitle: "The deadline wins when the market will not cooperate",
    symbol: "ETHUSDT",
    side: "BUY",
    quoteAmount: 750,
    maxSlippageBps: 12,
    deadlineSeconds: 60,
    minCompletionPct: 80,
    marketMode: "stress",
    simulatedFills: [0.28, 0.25, 0],
    market: { symbol: "ETHUSDT", bid: 4200, ask: 4204, midpoint: 4202, spreadBps: 9.5, dailyQuoteVolume: 420000000, priceChangePercent24h: -1.1, source: "Guardian stress-test fixture" },
    prompt: "Buy $750 of ETH in one minute. Stop at the deadline if the remaining fill breaks my price limit.",
  },
};
